// SPDX-License-Identifier: BSD-2-Clause
//! Generated tonic code for SatL's internal node-to-node gRPC protocol.
//!
//! The protocol definition lives in `proto/` at the repository root and is
//! described in `docs/architecture.md` §7 (internal protocols). This crate is
//! only the generated transport: it holds no logic, and the servers and clients
//! are implemented by the crates that own each concern —
//! `satld`/`satl-agent` (dispatcher), `satl-ca` (`NodeCA`), `satl-cluster`
//! (Raft, Control).
//!
//! # Scope
//!
//! **This protocol is internal only.** It is spoken between SatL nodes over
//! mTLS and is never exposed to clients; the Docker Engine REST API is the
//! external surface (`docs/api-compat.md`, architecture §13).
//!
//! # Services
//!
//! | Service | Role required | Defined in | Reference |
//! |---|---|---|---|
//! | [`Dispatcher`](v1::dispatcher_server::Dispatcher) | worker or manager | `proto/dispatcher.proto` | architecture §7.1, SWK §13 |
//! | [`NodeCA`](v1::node_ca_server::NodeCa) | none (bootstrap) / any | `proto/ca.proto` | architecture §12.2–§12.3, SWK §16.2–§16.3 |
//! | [`Raft`](v1::raft_server::Raft) | manager | `proto/raft.proto` | architecture §6, SWK §11.7 |
//! | [`Control`](v1::control_server::Control) | manager | `proto/control.proto` | architecture §6.5–§6.6, SWK §11.3, §11.5 |
//! | [`Health`](health::health_server::Health) | any | `proto/health.proto` | architecture §7 |
//!
//! # Payloads are opaque
//!
//! Store objects and openraft messages travel as `bytes` holding the CBOR
//! (`ciborium`) encoding of the corresponding `satl-core` / openraft type,
//! alongside the few scalars the protocol routes on. The rationale and the
//! tradeoff are written up at the top of `proto/common.proto` and in
//! `proto/README.md`; the short version is that `satl-core` stays the single
//! source of truth for the domain model, at the cost of cross-language
//! clients — which an internal protocol does not need.
//!
//! Every `bytes` payload in this crate is CBOR of the Rust type named in the
//! `.proto` comment. Changing that codec is a breaking change and requires a
//! new package version (`satl.internal.v2`).
//!
//! # Limits
//!
//! Messages are capped at 4 MiB (architecture §15). That bound is what forces
//! assignment batching (100 changes / 100 ms), status batching, and snapshot
//! chunking to exist at all — see the per-service comments in `proto/`.

/// The `satl.internal.v1` package: `Dispatcher`, `NodeCA`, `Raft`, `Control`
/// and the shared object envelopes.
///
/// Generated by `tonic-prost-build`; see `proto/` for the definitions and the
/// documentation, which is reproduced on the generated items.
// The workspace gates on `clippy::pedantic -D warnings` (see the root
// Cargo.toml) and generated code cannot be made to satisfy it: prost emits
// `#[derive(...)]`-heavy structs with `i32` enum fields, `as` casts in the
// enum helpers, and `unwrap`-free but pedantic-unfriendly builder plumbing.
// Suppressing at the module boundary keeps the gate strict for every
// hand-written line in the workspace while accepting that this module's
// contents are a build artifact. `rustdoc::all` is included for the same
// reason: comments copied from `.proto` files are prose, not rustdoc, and
// bracketed references in them would otherwise trip the intra-doc-link lint
// and make `cargo doc` noisy.
#[allow(clippy::pedantic, clippy::all, rustdoc::all)]
pub mod v1 {
    tonic::include_proto!("satl.internal.v1");
}

/// The standard `grpc.health.v1` health-checking service.
///
/// SatL registers the short service names `raft` and `control` (plus the empty
/// name for the whole server); `Control.JoinRaft` probes `raft` on a joining
/// manager before admitting it to the quorum. See `proto/health.proto`.
// See the note on `v1` for why generated code is exempted from the lint gate.
#[allow(clippy::pedantic, clippy::all, rustdoc::all)]
pub mod health {
    tonic::include_proto!("grpc.health.v1");
}

/// Maximum size of any message on the internal gRPC protocol
/// (architecture §15).
///
/// Apply it explicitly on both ends — tonic's defaults are not this value:
/// `.max_decoding_message_size(MAX_MESSAGE_SIZE)` and
/// `.max_encoding_message_size(MAX_MESSAGE_SIZE)` on every generated client and
/// server. Everything that batches or chunks in this protocol (assignment
/// batches, status batches, raft snapshot chunks) exists to stay under it.
pub const MAX_MESSAGE_SIZE: usize = 4 * 1024 * 1024;

#[cfg(test)]
mod tests {
    use super::{health, v1};

    /// The sparse SwarmKit values (architecture §4, SWK §4.2) are the contract
    /// between the wire, the Raft store and the agent's on-disk task database.
    /// If this test fails, the wire and the store have stopped agreeing.
    #[test]
    fn task_state_values_match_the_swarmkit_table() {
        let expected = [
            (v1::TaskState::New, 0),
            (v1::TaskState::Pending, 64),
            (v1::TaskState::Assigned, 192),
            (v1::TaskState::Accepted, 256),
            (v1::TaskState::Preparing, 320),
            (v1::TaskState::Ready, 384),
            (v1::TaskState::Starting, 448),
            (v1::TaskState::Running, 512),
            (v1::TaskState::Complete, 576),
            (v1::TaskState::Shutdown, 640),
            (v1::TaskState::Failed, 704),
            (v1::TaskState::Rejected, 768),
            (v1::TaskState::Remove, 800),
            (v1::TaskState::Orphaned, 832),
        ];
        for (state, value) in expected {
            assert_eq!(state as i32, value, "{state:?}");
        }
    }

    /// Desired states reuse the observed-state numbering so the two compare on
    /// one scale (architecture §4 rule 3).
    #[test]
    fn desired_state_values_line_up_with_task_state() {
        let pairs = [
            (v1::DesiredState::Ready, v1::TaskState::Ready),
            (v1::DesiredState::Running, v1::TaskState::Running),
            (v1::DesiredState::Complete, v1::TaskState::Complete),
            (v1::DesiredState::Shutdown, v1::TaskState::Shutdown),
            (v1::DesiredState::Remove, v1::TaskState::Remove),
        ];
        for (desired, observed) in pairs {
            assert_eq!(desired as i32, observed as i32, "{desired:?}");
        }
        assert_eq!(v1::DesiredState::Unspecified as i32, 0);
    }

    /// proto3 enums are open: an unknown value arrives as a bare `i32` and
    /// `try_from` is the only thing standing between it and a wrong decision.
    /// The implementing wave must reject both unknown and `UNSPECIFIED`.
    #[test]
    fn unknown_enum_values_do_not_decode() {
        assert!(v1::TaskState::try_from(513).is_err());
        assert!(v1::NodeRole::try_from(99).is_err());
        assert_eq!(
            v1::NodeRole::try_from(0),
            Ok(v1::NodeRole::Unspecified),
            "UNSPECIFIED decodes; callers must still treat it as a protocol error"
        );
    }

    /// The envelopes carry an opaque CBOR payload plus routing mirrors; this
    /// pins the shape so a later "helpful" re-modelling of the domain into
    /// protobuf shows up as a failing test rather than as drift.
    #[test]
    fn task_envelope_carries_an_opaque_payload_and_routing_mirrors() {
        let task = v1::Task {
            id: "1hvy0lj3x0b883f8e30fyp217".to_owned(),
            meta: Some(v1::Meta {
                version: Some(v1::Version { index: 42 }),
                created_at: None,
                updated_at: None,
            }),
            state: v1::TaskState::Running as i32,
            desired_state: v1::DesiredState::Running as i32,
            payload: vec![0xa0], // CBOR empty map
        };
        assert_eq!(task.state(), v1::TaskState::Running);
        assert_eq!(task.desired_state(), v1::DesiredState::Running);
        assert_eq!(task.payload, vec![0xa0]);
    }

    /// Assignment changes are a oneof of the three shipped object kinds; a
    /// REMOVE only needs the ID.
    #[test]
    fn assignment_change_models_remove_by_id() {
        let change = v1::AssignmentChange {
            assignment: Some(v1::Assignment {
                item: Some(v1::assignment::Item::Secret(v1::Secret {
                    id: "sec".to_owned(),
                    meta: None,
                    payload: Vec::new(),
                })),
            }),
            action: v1::assignment_change::Action::Remove as i32,
        };
        assert_eq!(change.action(), v1::assignment_change::Action::Remove);
        match change.assignment.and_then(|a| a.item) {
            Some(v1::assignment::Item::Secret(s)) => {
                assert_eq!(s.id, "sec");
                assert!(s.payload.is_empty());
            }
            other => panic!("expected a secret assignment, got {other:?}"),
        }
    }

    /// The health service is the upstream `grpc.health.v1` shape, so external
    /// probes work unchanged.
    #[test]
    fn health_serving_status_matches_upstream() {
        use health::health_check_response::ServingStatus;
        assert_eq!(ServingStatus::Unknown as i32, 0);
        assert_eq!(ServingStatus::Serving as i32, 1);
        assert_eq!(ServingStatus::NotServing as i32, 2);
        assert_eq!(ServingStatus::ServiceUnknown as i32, 3);
    }
}
