[package]
name = "satl-dispatcher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ciborium = "0.2.2"
prost-types = "0.14.4"
rand = "0.10.2"
satl-agent = { version = "0.2.0", path = "../satl-agent" }
satl-ca = { version = "0.2.0", path = "../satl-ca" }
satl-cluster = { version = "0.2.0", path = "../satl-cluster" }
satl-core = { version = "0.2.0", path = "../satl-core" }
satl-proto = { version = "0.2.0", path = "../satl-proto" }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt", "sync", "time", "macros"] }
tokio-stream = "0.1.19"
tokio-util = "0.7.19"
tonic = "0.14.6"
tracing = "0.1.44"

[dev-dependencies]
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { version = "0.3.23", features = ["registry"] }
